<?php

/**
 * Plugin Name: RH Admin Utilities
 * Plugin URI: https://github.com/hirasso/rh-admin-utils
 * Version: 4.0.1
 * Requires PHP: 8.4
 * Author: Rasso Hilber
 * Description: Admin Utilities for WordPress. Removes plugin ads, adds custom buttons to the admin bar (publish, clear cache), allows editors to add users (except administrators), disables comments. Provides filters to adjust functionality.
 * Author URI: https://rassohilber.com
 * License: GPL-2.0-or-later
 **/

declare(strict_types=1);

namespace RH\AdminUtils;

use RH\AdminUtils\SimplyStatic\SimplyStatic;

// Exit if accessed directly
if (!defined('ABSPATH')) {
    exit;
}

/**
 * Autoload this plugin's own classes.
 *
 * Registered by hand instead of relying on a composer autoloader, so that the plugin
 * loads identically whether it was installed via composer (where the site's root
 * autoloader owns the psr-4 mapping) or unpacked from the release zip (where no
 * plugin-local vendor/ exists at all).
 */
spl_autoload_register(static function (string $class): void {
    if (!str_starts_with($class, __NAMESPACE__ . '\\')) {
        return;
    }

    $relative = substr($class, strlen(__NAMESPACE__) + 1);

    /** The prefixed dependencies share this namespace but are autoloaded by Strauss */
    if (str_starts_with($relative, 'Vendor\\')) {
        return;
    }

    $file = __DIR__ . '/src/' . str_replace('\\', '/', $relative) . '.php';

    if (is_readable($file)) {
        require_once $file;
    }
});

/**
 * Require the prefixed dependencies, generated by Strauss and committed to the repo.
 * @see https://github.com/BrianHenryIE/strauss
 */
require_once __DIR__ . '/vendor-prefixed/autoload.php';

/**
 * The `RH\AdminUtils\dump()`/`dd()` helpers, which route to the prefixed var-dumper
 */
require_once __DIR__ . '/src/functions.php';

/**
 * Re-serve `dump()` and `dd()` globally, unless opted out of in wp-config.php
 */
if (!defined('RHAU_GLOBAL_DEBUG_FUNCTIONS') || RHAU_GLOBAL_DEBUG_FUNCTIONS) {
    require_once __DIR__ . '/src/global-functions.php';
}

/** Get the plugin's base URL */
function baseURL()
{
    return plugins_url('', __FILE__);
}

/** Get the plugin's base directory */
function baseDir()
{
    return __DIR__;
}

function pluginFile()
{
    return __FILE__;
}

/**
 * Initialize main class
 */
AdminUtils::getInstance();

/**
 * Make AdminUtils instance available API calls
 *
 * @return AdminUtils
 */
function rhau()
{
    return AdminUtils::getInstance();
}


/**
 * Initialize the modules
 */
AdminBarPublishButton::getInstance();
ACFRestrictToPostTypes::init();
EditorsAddUsers::getInstance();
DisableComments::getInstance();
ACFRestrictFieldAccess::init();
WpscClearCache::getInstance();
PendingReviews::getInstance();
ACFPasswordUtilities::init();
ACFRelationshipField::init();
RolesAndCaps::getInstance();
Environments::getInstance();
Hardening\Hardening::init();
ACFSyncFieldGroups::init();
ACFOembedWhitelist::init();
ForceLowercaseURLs::init();
AttachmentsHelper::init();
RemoveAds::getInstance();
PageRestrictions::init();
PrettyPermalinks::init();
ACFSyncPostDate::init();
ACFOembedCache::init();
QueryOptimizer::init();
AdminDashboard::init();
TinyMcePlugins::init();
WpCliCommands::init();
SendTestEmail::init();
ACFCodeField::init();
SimplyStatic::init();
ACFTextField::init();
Misc::getInstance();

/**
 * Support for manual (non-composer) updates
 */
UpdateChecker::init(entryPoint: __FILE__);

/**
 * An automatically installed mu helper plugin
 */
new HelperPluginInstaller(__FILE__);
