<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInitcc04f03401a6c0cdcf09e24e37351b25
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('RH\AdminUtils\Vendor\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \RH\AdminUtils\Vendor\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInitcc04f03401a6c0cdcf09e24e37351b25', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \RH\AdminUtils\Vendor\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInitcc04f03401a6c0cdcf09e24e37351b25', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\RH\AdminUtils\Vendor\Composer\Autoload\ComposerStaticInitcc04f03401a6c0cdcf09e24e37351b25::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        $filesToLoad = \RH\AdminUtils\Vendor\Composer\Autoload\ComposerStaticInitcc04f03401a6c0cdcf09e24e37351b25::$files;
        $requireFile = \Closure::bind(static function ($fileIdentifier, $file) {
            if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
                $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;

                require $file;
            }
        }, null, null);
        foreach ($filesToLoad as $fileIdentifier => $file) {
            $requireFile($fileIdentifier, $file);
        }

        return $loader;
    }
}
