<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'RH\\AdminUtils\\Vendor\\Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
    'RH\\AdminUtils\\Vendor\\Symfony\\Component\\VarDumper\\' => array($vendorDir . '/symfony/var-dumper'),
);
