name: CI

on:
  push:
    branches:
      main
  pull_request:

permissions:
  contents: write # for merging the PR and creating the release
  pull-requests: write # for creating the version PR

# Cancel all previous workflow runs for pull requests that have not completed
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:

  phpTests:
    name: PHP ${{ matrix.php }} Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.2, 8.3, 8.4]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run Shared Setup
        uses: ./.github/actions/shared-setup
        with:
          php-version: ${{ matrix.php }}

      - name: Run PHPStan Tests
        run: composer analyse

      - name: Run Pest Tests
        run: pnpm run test:pest:ci

  e2eTests:
    name: E2E Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run Shared Setup
        uses: ./.github/actions/shared-setup
        with:
          php-version: 8.3
          playwright: true

      - name: Run E2E Tests
        run: |
          pnpm run test:e2e

      - uses: daun/playwright-report-summary@1229105480a2a4bdd91598d8a146fbab41343fce # v3.11.0
        if: always()
        with:
          report-file: playwright-results.json

  packageInfos:
    name: Get Package Infos
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: [phpTests, e2eTests]
    outputs:
      fullName: ${{ steps.packageInfos.outputs.fullName }}
      vendorName: ${{ steps.packageInfos.outputs.vendorName }}
      packageName: ${{ steps.packageInfos.outputs.packageName }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Read and Write Package Infos to Output
        id: packageInfos
        run: |
          NAME=$(jq -r '.name' composer.json)
          echo "fullName=${NAME}" >> $GITHUB_OUTPUT
          echo "vendorName=${NAME%%/*}" >> $GITHUB_OUTPUT
          echo "packageName=${NAME#*/}" >> $GITHUB_OUTPUT
          cat "$GITHUB_OUTPUT"

  release:
    needs: packageInfos
    if: ${{ github.repository == needs.packageInfos.outputs.fullName }}

    name: Create Version PR or Publish
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Configure Git
        run: |
          git config --global user.email "bot@rassohilber.com"
          git config --global user.name "Rasso Hilber's Bot"

      - name: Run Shared Setup
        uses: ./.github/actions/shared-setup
        with:
          php: false
          wp-env: false

      - name: Build and bundle assets
        run: |
          pnpm build
          zip -rq assets.zip assets

      - name: Checkout Distribution Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: ${{ needs.packageInfos.outputs.fullName }}-dist
          ref: empty
          path: dist
          # secrets.GITHUB_TOKEN is not enough to push to the dist repo (needed later)
          token: ${{ secrets.HIRASSO_ACTIONS_TOKEN }}

      # Run this before changesets, to make sure releases actually work
      - name: Create Release Files and Prepare Dist Folder
        run: |
          config/cli/cli.js release:create
          config/cli/cli.js dist:prepare

      # Run changesets action either if there are unreleased changesets (= a PR must be created)
      # or if the commit message matches the release PR (= new versions must be published to NPM)
      - name: Create changesets PR or Publish
        id: cs
        uses: changesets/action@6a0a831ff30acef54f2c6aa1cbbc1096b066edaf # v1.7.0
        with:
          title: "[CI] Release"
          commit: "[CI] Release"
          version: pnpm run version
          publish: pnpm changeset tag
        env:
          # do not run the pre-commit hook
          HUSKY: 0
          # doesn't work with GITHUB_TOKEN for some reason
          GITHUB_TOKEN: ${{ secrets.HIRASSO_ACTIONS_TOKEN }}

      - name: "Get Latest Tag"
        id: latest-tag
        uses: "WyriHaximus/github-action-get-previous-tag@61819f33034117e6c686e6a31dba995a85afc9de" # v2.0.0

      - name: Add artifacts to the latest release
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
        if: steps.cs.outputs.published == 'true'
        with:
          tag: ${{ steps.latest-tag.outputs.tag }}
          allowUpdates: true
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          artifacts: "${{ needs.packageInfos.outputs.packageName }}.zip,assets.zip"

      - name: Push release to dist repo
        if: steps.cs.outputs.published == 'true'
        run: |
          config/cli/cli.js dist:push
