name: Dynamic Repo Name


on:
  workflow_dispatch:
  push:

jobs:
  package-infos:
    name: Get Package Infos
    runs-on: ubuntu-latest
    outputs:
      fullName: ${{ steps.package-infos.outputs.fullName }}
      owner: ${{ steps.package-infos.outputs.owner }}
      name: ${{ steps.package-infos.outputs.name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read and Write Package Infos to Output
        id: package-infos
        run: |
          NAME=$(jq -r '.name' composer.json)
          echo "fullName=${NAME}" >> $GITHUB_OUTPUT
          echo "owner=${NAME%%/*}" >> $GITHUB_OUTPUT
          echo "name=${NAME#*/}" >> $GITHUB_OUTPUT

      - name: Debug package infos
        run: |
          echo "fullName: ${{ steps.package-infos.outputs.fullName }}"
          echo "owner: ${{ steps.package-infos.outputs.owner }}"
          echo "name: ${{ steps.package-infos.outputs.name }}"

  release:
    name: Create Version PR or Publish
    runs-on: ubuntu-latest

    needs: package-infos
    if: ${{ github.repository == needs.package-infos.outputs.fullName }}

    steps:
      - name: Dump `package-name`
        run: |
          echo "fullName: ${{ needs.package-infos.outputs.fullName }}"
          echo "owner: ${{ needs.package-infos.outputs.owner }}"
          echo "name: ${{ needs.package-infos.outputs.name }}"