name: Version or Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write  # for merging the PR and creating the release
  pull-requests: write # for creating the version PR

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    # Don't run on forks. We can and should only release from the main repo.
    if: github.repository == 'hirasso/rh-admin-utils'

    name: Create Version PR or Publish

    runs-on: ubuntu-latest

    steps:
      - name: Configure Git
        run: |
          git config --global user.email "bot@rassohilber.com"
          git config --global user.name "Rasso Hilber's Bot"

      - name: Check out repository
        uses: actions/checkout@v4

      # Setup PNPM first, so that we use the cache in the next action
      - name: Setup PNPM
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Require Build
        run: pnpm build

      # Run changesets action either if there are unreleased changesets (= a PR must be created)
      # or if the commit message matches the release PR (= new versions must be published to NPM)
      - name: Create changesets PR or Publish
        id: cs
        uses: changesets/action@v1
        with:
          title: '[CI] Release'
          commit: '[CI] Release'
          version: pnpm run version
          publish: pnpm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.HIRASSO_ACTIONS_TOKEN }}

      - name: Checkout dist repo
        uses: actions/checkout@v3
        # GitHub Actions outputs are strings and the string 'false' converts to
        # `true` because it isn't the empty string.
        if: steps.cs.outputs.published == 'true'
        with:
          repository: hirasso/rh-admin-utils-dist
          ref: empty
          path: dist
          # secrets.GITHUB_TOKEN would not be enough to push to the dist repo
          token: ${{ secrets.HIRASSO_ACTIONS_TOKEN }}

      - name: Push release to dist repo
        # GitHub Actions outputs are strings and the string 'false' converts to
        # `true` because it isn't the empty string.
        if: steps.cs.outputs.published == 'true'
        # working-directory: dist
        run: |
          echo "Package was published (${PACKAGE_VERSION}). A release will be pushed."
          PACKAGE_VERSION=$(node ./scripts/logVersion.js)

          if [[ -z "$PACKAGE_VERSION" ]]; then
            echo "Empty package version. Exiting."
            exit 1
          fi

          echo "Checking out the empty root commit..."
          git -C dist checkout --detach empty

          echo "Building release files..."
          ./scripts/prefixNamespaces.sh

          echo "Injecting release files..."
          ./scripts/createDistFolder.sh

          echo "Committing and pushing new release: '${PACKAGE_VERSION}'..."
          cd dist/
          git add .
          git commit -m "Release: rh-admin-utils@${PACKAGE_VERSION}"
          git tag "${PACKAGE_VERSION}"
          git push origin "${PACKAGE_VERSION}"

          echo "Done."