name: Version or Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write  # for Git to git push
  pull-requests: write # to allow creating PR

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    # Don't run on forks. We can and should only release from the main repo.
    if: github.repository == 'hirasso/rh-admin-utils'

    name: Create Version PR or Publish

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # Setup PNPM first, so that we use the cache in the next action
      - name: Setup PNPM
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Require Build
        run: pnpm build

      # Run changesets action either if there are unreleased changesets (= a PR must be created)
      # or if the commit message matches the release PR (= new versions must be published to NPM)
      - name: Create changesets PR or publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          title: '[CI] Release'
          commit: '[CI] Release'
          version: pnpm run version
          publish: pnpm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}